"""indexed short_code on url model

Revision ID: 2ef06a4c2a95
Revises: 198be948566f
Create Date: 2026-09-24 12:53:59.553686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef06a4c2a95'
down_revision: Union[str, Sequence[str], None] = '198be948566f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_short_code_key'), 'urls', type_='unique')
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.create_unique_constraint(op.f('urls_short_code_key'), 'urls', ['short_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
