"""added Click model for url analytics

Revision ID: 9a361fa5c255
Revises: 546230c94d14
Create Date: 2026-09-26 17:18:08.363849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a361fa5c255'
down_revision: Union[str, Sequence[str], None] = '546230c94d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('url_uuid', sa.UUID(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('referrer', sa.String(length=1000), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['url_uuid'], ['urls.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_clicks_url_uuid'), 'clicks', ['url_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_url_uuid'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###
